### PR TITLE
Added New Relic configuration.

### PR DESCRIPTION
**Pull request by kylanee**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
Checking now.

**Review by ghost — CHANGES_REQUESTED** [review]
Did you add the New Relic package to the dependency list? Make sure to add it to the **backend** project.

**Review by ghost — CHANGES_REQUESTED** [review]
I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update "docker-compose.yml". Please make sure to revert your changes before merging your PR.

**Review by ghost — CHANGES_REQUESTED** [review]
I see you've committed a license key to Git. Shouldn't do that, security-wise. Please remove the entire property from the config file, we'll add it as an environment variable.

**Review by ghost — APPROVED** [review]
Looking good! You can merge the PR now.

**Review by vanessa-cooper — APPROVED** [review]

**Pull request merged**
